[build-system]
requires = ["setuptools>=61.0", "packaging"]
build-backend = "setuptools.build_meta"

[project]
name = "imas-standard-interfaces"
version = "0.1.0"
description = "Standardized schemas and interfaces for scientific data formats used in IMAS."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "imas-python>=2.3.0",
    "jsonschema>=4.26.0",
    "pyyaml>=6.0.3",
    "netCDF4>=1.7.0"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
'interfaceTools' = ['../schemas/json_schema.json']

[project.scripts]
imas-interfaces = "interfaceTools.cli:main"
