name: Try some functionaltiy of github actions

on:
  push: # Remove this line before removing draft status of PR 


jobs:
  tryout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git related stuff
        run: |
          git status
          git branch
          git log -2

      - name: Change file and push
        run: |
          echo "# SOME CHANGE" >> schemas/validate_definitions.py
          git add schemas/validate_definitions.py
          git commit -m "Github Actions: update script"
          git push
          git log -3
