name: Validate example definitions against schema

on:
  pull_request:
    types: [opened, closed]
    branches: 
      - main
      - 'releases/**'
      - 'tmp/try_**' # Very specifi

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv version
          uv sync

      - name: Run validation script
        run: |
          if [[ "$(uv run python schemas/validate_definitions.py example_definitions/ | tail -1)" == "No issues found" ]];
          then exit 0;
          else exit 1;
          fi
      - name: Some last command
        run: echo "github.event.pull_request.merged = $({ github.event.pull_request.merged})"

      - name: Some really last command
        run: echo "github.event.workflow_run.conclusion = $({ github.event.workflow_run.conclusion})"
